
services:
  postgres:
    image: postgres:16-alpine
    container_name: personal-library-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal_library

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - library-network

  backend:
    build:
      context: ./libraryservice
      dockerfile: Dockerfile

    container_name: personal-library-api

    ports:
      - "3000:3000"

    env_file:
      - ./libraryservice/.env

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./libraryservice:/app
      - /app/node_modules

    command: sh -c "npx prisma migrate deploy && npm run dev"

    networks:
      - library-network

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge